import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Feed from "src/components/Feed";

const Home: NextPage = () => {
  /* const { data: sessionData } = useSession(); */

  return (
    <>
      <Head>
        <link
          rel="stylesheet prefetch"
          href="https://cdn.rawgit.com/mfd/e7842774e037edf15919037594a79b2b/raw/665bdfc532094318449f1010323c84013d5af953/graphik.css"
        />
        <title>Join Nova Clone</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width" />
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="" />
      </Head>
      <div className="md:h-full md:px-4 lg:px-8 xl:px-[72px]">
        <div className="m-auto w-full sm:h-full md:h-full lg:max-w-[1400px]">
          <div className="flex flex-wrap px-[16px] pt-16 sm:h-full md:h-full md:px-0 md:pt-8 lg:px-4">
            <Feed />
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
